account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views_account
from django.urls.conf import include

app_name = 'account'

urlpatterns = [
    path('login/', views_account.login_form, name='login'),
    path('forgotpsw/', views_account.forgot_psw, name='forgotpsw'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('change_password/',
          views_account.CustomPasswordChangeView.as_view(
            template_name='change_password.html', success_url="/"), name='change_password'),
    path('reset_password_confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
            template_name='reset_password_confirm.html', success_url="/?message=The%20password%20is%20successfully%20changed&T=false"), name='reset_password_confirm'),
    path('reset_password/',
          auth_views.PasswordResetView.as_view(
            template_name='reset_password.html',
            email_template_name='reset_password_email.html', success_url="/?message=A%20confirmation%20email%20is%20sent%20to%20your%20email%20address&T=false"), name='reset_password'),
    path('userlist/', views_account.projectUserList, name='userlist'),
    path('register/', views_account.registration, name='register'),
    path('register_judge/', views_account.registerJudge, name='registerJudge'),
]

evaluation/urls.py
from django.urls import path
from evaluation import views_evaluation

app_name = 'evaluation'

urlpatterns = [
    # re_path(r'^index/$', views.index, name='index'),
    path('formd1a/', views_evaluation.create_d1a, name='formd1a'),
    path('formd1b/', views_evaluation.create_d1b, name='formd1b'),
    path('formd2/', views_evaluation.create_d2, name='formd2'),
    path('formd3/', views_evaluation.create_d3, name='formd3'),
    path('eval_forms_artwork/', views_evaluation.eval_forms_artwork, name='eval_forms_artwork'),
    path('updateAllD2s/', views_evaluation.updateWorkJudge2to3, name='updateAllD2s'),
]

mathart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('artwork.urls', namespace='artwork')),
    path('evaluation/', include('evaluation.urls', namespace='evaluation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/evaluationForms/D1A_form.html
<div class="row page-title">
	<div class="col-md-12">
		<h5>Evaluation Form, Primary Decision</h5>
	</div>
</div>
<hr>
<form method="post" action="{% url 'evaluation:formd1a' %}"
	class="needs-validation form-general-style" id="formd1aId"
	enctype="multipart/form-data" novalidate>
	<input type="hidden" value="{{ request.GET.work_id }}" name="work_id">
	<input type="hidden" value="{{ form.id|default:'0' }}" name="id"
		id="id">
	<div class="row">
		<div class="col-md-4">
			<label for="ImageQuality{{ form.id }}">Image Quality</label> <select
				class="custom-select" name="imgq" id="ImageQuality{{ form.id }}">
				<option value="">--</option>
				<option value="0">None</option>
				<option value="1">Minimal</option>
				<option value="2">Average</option>
				<option value="3">Good</option>
				<option value="4">Excellent</option>
			</select> <input type="hidden" value="{{ form.imgq|default:'0' }}"
				id="imgqid{{ form.id }}">
		</div>
		<div class="col-md-4">
			<label for="AnswersScore{{ form.id }}">Answers to the
				questions</label> <select class="custom-select" name="answersq"
				id="AnswersScore{{ form.id }}">
				<option value="">--</option>
				<option value="0">None</option>
				<option value="1">Minimal</option>
				<option value="2">Average</option>
				<option value="3">Good</option>
				<option value="4">Excellent</option>
			</select> <input type="hidden" value="{{ form.answersq|default:'0' }}"
				id="answerqid{{ form.id }}">
		</div>
		<div class="col-md-4">
			<label for="OriginQuality{{ form.id }}">Originiality of the
				work</label> <select class="custom-select" name="originq"
				id="OriginQuality{{ form.id }}">
				<option value="">--</option>
				<option value="0">None</option>
				<option value="1">Minimal</option>
				<option value="2">Average</option>
				<option value="3">Good</option>
				<option value="4">Excellent</option>
			</select> <input type="hidden" value="{{ form.originq|default:'0' }}"
				id="originq{{ form.id }}">
		</div>
		<br>
		<div class="col-md-12">
			<label for="comment">Comments</label>
			<textarea class="form-control form-input" id="comment"
				placeholder="Please add any comments, if there are some..."
				name="comment" rows="5">{{ form.comment|default_if_none:'' }}</textarea>
		</div>
	</div>
	<hr>
	<div class="row buttons-holder-div">
		<div class="col-md-6 text-center">
			<!-- 		THE FUNCTION TO SUBMIT A FORM TAKES AN ACTION URL, THE FORM ID AND THE SUBMIT BUTTON ID -->
			<button class="btn btn-block btn-success" type="button"
				id="buttonSubmitD1AForm" onclick="toggleConfirmationBox(submitAnEvaluationForm,'Do you want to submit the evaluation form?','{% url 'evaluation:formd1a' %}','formd1aId','buttonSubmitD1AForm', null)">
				<i class="fa fa-check-circle">&nbsp;&nbsp;&nbsp;</i>Submit
			</button>
		</div>
		<div class="col-md-6 text-center">
			<button class="btn btn-block btn-outline-warning" type="button"
				onclick="closeFullScreenDiv()">
				<i class="fa fa-times-circle">&nbsp;&nbsp;&nbsp;</i>Close
			</button>
		</div>
	</div>
	{% csrf_token %}
</form>

<script type="text/javascript">
$(document).ready(function(){
	$("#OriginQuality{{ form.id }} option[value="
			+ $("#originq{{ form.id }}").val() + "]").attr(
	'selected','selected')
	$("#AnswersScore{{ form.id }} option[value="
					+ $("#answerqid{{ form.id }}").val() + "]").attr(
			'selected','selected')
	$("#ImageQuality{{ form.id }} option[value="
					+ $("#imgqid{{ form.id }}").val() + "]").attr(
			'selected','selected')
})
</script>

templates/evaluationForms/D1B_form.html
<div class="row page-title">
	<div class="col-md-4">
		<strong>User:</strong>&nbsp; {{ form.author }}
	</div>
	<div class="col-md-8">
		<h5>Evaluation Form, Decision Making</h5>
	</div>
</div>
<hr>
<form method="post" action="{% url 'evaluation:formd1b' %}"
	class="needs-validation form-general-style" id="formd1bId"
	enctype="multipart/form-data" novalidate>
	<input type="hidden" value="{{ request.GET.work_id }}" name="work_id">
	<input type="hidden" value="{{ form.id|default:'0' }}"
		name="id" id="id">
	<input type="hidden" name="status" value="0" id="statusfield">
	<div class="row">
		<div class="col-md-12">
			<label for="comment">Comments</label>
			<textarea class="form-control form-input" id="comment"
				placeholder="Please add any comments, if there are some..."
				name="comment" rows="5">{{ form.comment|default_if_none:'' }}</textarea>
		</div>
	</div>
	<hr>
	<div class="row buttons-holder-div">
		<div class="col-md-4 text-center">
			<!-- 		THE FUNCTION TO SUBMIT A FORM TAKES AN ACTION URL, THE FORM ID AND THE SUBMIT BUTTON ID -->
			<button class="btn btn-block btn-success" type="button" id="buttonSubmitD1BForm"
				onclick="toggleConfirmationBox(submitAnEvaluationForm,'Are you sure that the work is approved?','{% url 'evaluation:formd1b' %}','formd1bId','buttonSubmitD1BForm', '6')">
				<i class="fa fa-check">&nbsp;&nbsp;&nbsp;</i>Accept
			</button>
		</div>
		<div class="col-md-4 text-center">
			<!-- 		THE FUNCTION TO SUBMIT A FORM TAKES AN ACTION URL, THE FORM ID AND THE SUBMIT BUTTON ID -->
			<button class="btn btn-block btn-outline-danger" type="button"
				onclick="toggleConfirmationBox(submitAnEvaluationForm,'Are you sure that the work is rejected?','{% url 'evaluation:formd1b' %}','formd1bId','buttonSubmitD1BForm', '7')">
				<i class="fa fa-times">&nbsp;&nbsp;&nbsp;</i>Reject
			</button>
		</div>
		<div class="col-md-4 text-center">
			<button class="btn btn-block btn-outline-warning" type="button"
				onclick="closeFullScreenDiv()">
				<i class="fa fa-times-circle">&nbsp;&nbsp;&nbsp;</i>Close
			</button>
		</div>
	</div>
	{% csrf_token %}
</form>

templates/evaluationForms/D2_form.html
<style>
.row.form-section .col-md-2 {
	text-align: center;
}
</style>
<div class="page-title">
	<h2>Evaluation Form Stage 2</h2>
</div>
<hr>
<form method="post" action="{% url 'evaluation:formd2' %}"
	class="needs-validation form-general-style" id="formd2Id"
	enctype="multipart/form-data" novalidate>
<input type="hidden" value="{{ request.GET.work_id }}" name="work_id">
	<input type="hidden" value="{{ form.instance.id|default:'0' }}"
		name="id" id="id">
	<div class="row">
		<div class="col-md-12">"What mathematics was used? (Please select one or more checkboxes)"</div>
	</div>
	<div class="row form-section" id="math">
		{% for x, y in form.fields.math.base_field.choices %} {% if x != '' %}
		{%if forloop.counter < 9 %}
			{%if forloop.counter == 2 %}
		<div class="card col-md-6 text-white bg-primary"><div class="card-header collapsed row" data-toggle="collapse"
				href="#algebra">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-divide"></i>&nbsp;&nbsp;&nbsp;Algebra</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="collapse card-body" id="algebra">
			{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
			</div>
		{% elif forloop.counter < 12 %}
		{%if forloop.counter == 9 %}
		</div></div>
		<div class="card col-md-6 text-white bg-secondary">
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#rf">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-bezier-curve"></i>&nbsp;&nbsp;&nbsp;Relations & Functions</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="rf">
		{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label></div>
		{% elif forloop.counter < 21 %}
		{%if forloop.counter == 12 %}
		</div></div>
		<div class="card col-md-6 text-white bg-success">
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#geometry">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-shapes"></i>&nbsp;&nbsp;&nbsp;Geometry</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="geometry">
		{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
			</div>
		{% elif forloop.counter < 25 %}
		{%if forloop.counter == 21 %}
		</div></div>
		<div class="card col-md-6 text-white bg-danger">
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#measurement">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-ruler-combined"></i>&nbsp;&nbsp;&nbsp;Measurement</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="measurement">
		{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
			</div>
		{% elif forloop.counter < 28 %}
		{% if forloop.counter == 25 %}
		</div></div>
		<div class="card col-md-6 text-white bg-warning">
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#Trigonometry">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-percent"></i>&nbsp;&nbsp;&nbsp;Trigonometry</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="Trigonometry">
		{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
			</div>
			{% elif forloop.counter > 27 %}
		{%if forloop.counter == 28 %}
		</div></div>
		<div class="card col-md-6 text-white bg-info">
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#Statistics">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-chart-bar"></i>&nbsp;&nbsp;&nbsp;Statistics</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="Statistics">
		{% endif %}
			<div class="form-check">
				<input class="form-check-input" type="checkbox"
					id="inlineCheckbox{{ x }}" value="{{ x }}" name="math" {% if x in form.instance.math %} checked {% endif %}>
				<label class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
			</div>
		{% endif %}
		{% endif %}
		
		 {% endfor %}
		 </div></div>
		<div class="col-md-12">
	</div>
	</div>
	<div class="row form-section" id="q1"
		data-title="Was the mathematics correctly applied?">
		<br>
		<div class="col-md-2">
			<label>Excellent</label> <input type="hidden"
				class="form-control form-input"
				value="{{ form.instance.imgq|default_if_none:'' }}" required>
			<input type="radio" class="form-control form-input" name="q1radio"
				value="4">
		</div>
		<div class="col-md-2">
			<label>Good</label> <input type="radio"
				class="form-control form-input" name="q1radio" value="3">
		</div>
		<div class="col-md-2">
			<label>Average</label> <input type="radio"
				class="form-control form-input" name="q1radio" value="2">
		</div>
		<div class="col-md-2">
			<label>Minimal</label> <input type="radio"
				class="form-control form-input" name="q1radio" value="1">
		</div>
		<div class="col-md-2">
			<label>None</label> <input type="radio"
				class="form-control form-input" name="q1radio" value="0">
		</div>
		<div class="col-md-2">
			 <input type="hidden"
				class="form-control form-input" name="q1radioscore" value="">
			<input type="hidden" class="form-control form-input question-value"
				name="q1" value="{{ form.instance.q1 }}">
		</div>
	</div>
	<hr>
	<div class="row form-section" id="q2"
		data-title="How well was the connection between Mathematics and the artwork explained in the paragraph?">
		<br>
		<div class="col-md-2">
			<label>Excellent</label> <input type="hidden"
				class="form-control form-input"
				value="{{ form.instance.imgq|default_if_none:'' }}" required>
			<input type="radio" class="form-control form-input" name="q2radio"
				value="4">
		</div>
		<div class="col-md-2">
			<label>Good</label> <input type="radio"
				class="form-control form-input" name="q2radio" value="3">
		</div>
		<div class="col-md-2">
			<label>Average</label> <input type="radio"
				class="form-control form-input" name="q2radio" value="2">
		</div>
		<div class="col-md-2">
			<label>Minimal</label> <input type="radio"
				class="form-control form-input" name="q2radio" value="1">
		</div>
		<div class="col-md-2">
			<label>None</label> <input type="radio"
				class="form-control form-input" name="q2radio" value="0">
		</div>
		<div class="col-md-2">
			<input type="hidden"
				class="form-control form-input" name="q2radioscore" value="">
			<input type="hidden" class="form-control form-input question-value"
				name="q2" value="{{ form.instance.q2 }}">
		</div>
	</div>
	<hr>
	<div class="row form-section" id="q3"
		data-title="How creative/original/clever is the connection with Mathematics?">
		<div class="col-md-2">
			<label>Excellent</label> <input type="hidden"
				class="form-control form-input"
				value="{{ form.instance.imgq|default_if_none:'' }}" required>
			<input type="radio" class="form-control form-input" name="q3radio"
				value="4">
		</div>
		<div class="col-md-2">
			<label>Good</label> <input type="radio"
				class="form-control form-input" name="q3radio" value="3">
		</div>
		<div class="col-md-2">
			<label>Average</label> <input type="radio"
				class="form-control form-input" name="q3radio" value="2">
		</div>
		<div class="col-md-2">
			<label>Minimal</label> <input type="radio"
				class="form-control form-input" name="q3radio" value="1">
		</div>
		<div class="col-md-2">
			<label>None</label> <input type="radio"
				class="form-control form-input" name="q3radio" value="0">
		</div>
		<div class="col-md-2">
			 <input type="hidden"
				class="form-control form-input" name="q3radioscore"> <input
				type="hidden" class="form-control form-input question-value" name="q3"
				value="{{ form.instance.q3 }}">
		</div>
	</div>
	<hr>
	<div class="row form-section" id="q4"
		data-title="How clear is the Mathematics visually portrayed in the artwork?">
		<div class="col-md-2">
			<label>Excellent</label> <input type="hidden"
				class="form-control form-input"
				value="{{ form.instance.imgq|default_if_none:'' }}" required>
			<input type="radio" class="form-control form-input" name="q4radio"
				value="4">
		</div>
		<div class="col-md-2">
			<label>Good</label> <input type="radio"
				class="form-control form-input" name="q4radio" value="3">
		</div>
		<div class="col-md-2">
			<label>Average</label> <input type="radio"
				class="form-control form-input" name="q4radio" value="2">
		</div>
		<div class="col-md-2">
			<label>Minimal</label> <input type="radio"
				class="form-control form-input" name="q4radio" value="1">
		</div>
		<div class="col-md-2">
			<label>None</label> <input type="radio"
				class="form-control form-input" name="q4radio" value="0">
		</div>
		<div class="col-md-2">
			<input type="hidden"
				class="form-control form-input" name="q4radioscore"> <input
				type="hidden" class="form-control form-input question-value" name="q4"
				value="{{ form.instance.q4 }}">
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			Total Score
		</div>
		<div class="col-md-4" id="scorediv">
			{{ form.instance.score|default_if_none:'0' }}
		</div>
		<div class="col-md-6">
		<label>Comment</label>
				<textarea class="
			form-control form-input" id="comment"
			placeholder="Please add any comments, if there are some..."
			name="comment" rows="5">{{ form.instance.comment|default_if_none:'' }}</textarea>
		</div>
	</div>
<hr>
	<div class="row buttons-holder-div">
	<div class="col-md-6 text-center">
		<button class="btn btn-block btn-success" type="button" id="buttonSubmitD2Form"
				onclick="toggleConfirmationBox(submitAnEvaluationForm,'Do you want to submit the evaluation form?','{% url 'evaluation:formd2' %}','formd2Id','buttonSubmitD2Form', null)"><i class="fa fa-save">&nbsp;&nbsp;&nbsp;</i>Submit</button>
	</div>
	<div class="col-md-6 text-center">
		<button class="btn btn-block btn-outline-warning" type="button" 
				onclick="closeFullScreenDiv()"><i class="fa fa-times-circle">&nbsp;&nbsp;&nbsp;</i>Close</button>
	</div>
	</div>
</form>
<script>
	$(document).ready(
			function() {
				$("#formd2Id").find("input[type='radio']").each(function() {
					$("#formd2Id").find("input[name='" + $(this).attr("name") + "score']").val(parseInt($(this).val() * 6.25) + "%")
					$(this).change(function() {
						$("input[name='" + $(this).attr("name") + "score']").val(parseInt($(this).val() * 6.25)+ "%")
						var q = $(this).attr("name").replace('radio','')
						$("input[name='"+q+"']").val($(this).val())
						calculateTotalD2()
					})
			})
			$("#formd2Id").find(".question-value").each(
					function() {
						$("#formd2Id").find("input[type='radio'][name='" + $(this).attr("name") + "radio'][value='"+$(this).val()+"']").prop("checked", true)
					})
			calculateTotalD2()
			})
	function calculateTotalD2() {
		var val = 0
		$("#formd2Id").find(".question-value").each(function(){
			val += parseInt($(this).val() * 6.25)
			$("#formd2Id").find("#scorediv").html(val + "%")
		})
	}
</script>

templates/evaluationForms/eval_forms.html
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8 card eval-form">
		{% if d1as or d1bs or d2 or d3%}
		<div class="card-header collapsed row" data-toggle="collapse"
			href="#eval-forms">
			<div class="col-md-11">
				<a class="card-title"><i class="fa fa-gavel"></i>&nbsp;&nbsp;&nbsp;Evaluation
					Results</a>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="collapse card-body" id="eval-forms">
			{% if d1as %} {% for d1a in d1as %}
			{% if  d1a.updated_at != d1a.created_at %}
			<div class="card-header collapsed row" data-toggle="collapse"
				aria-expanded="false" href="#eval-form-1-{{ forloop.counter }}" data-id="d1a{{ d1a.id }}">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-gavel"></i>&nbsp;&nbsp;&nbsp;
						<!-- 					CARD HEADING -->
						Judge 1 ({{ d1a.author.last_name }}, {{ d1a.author.first_name }})</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row collapse card-body" id="eval-form-1-{{ forloop.counter }}" >
				<div class="col-md-4"><strong>Image Quality</strong>({% widthratio d1a.imgq 1 25 %}%)</div>
				<div class="col-md-4"><strong>Answers to the questions </strong>({% widthratio d1a.answersq 1 25 %}%)</div>
				<div class="col-md-4"><strong>Originiality of the work </strong>({% widthratio d1a.originq 1 25 %}%)</div>
				<div class="col-md-12"><strong>Comment </strong>{{ d1a.comment }}</div>
			</div>
			{% endif %}{% endfor %}<hr> {% endif %}
			{% if d1bs %} {% for d1b in d1bs %}{% if  d1b.updated_at != d1b.created_at %}
			<div class="card-header collapsed row" data-toggle="collapse" data-id="d1b{{ d1b.id }}"
				aria-expanded="false" href="#eval-form-dm-{{ forloop.counter }}">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-gavel"></i>&nbsp;&nbsp;&nbsp;
						<!-- 					CARD HEADING --> 
						Decision Maker ({{ d1b.author.last_name }}, {{ d1b.author.first_name }})</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row collapse card-body"
				id="eval-form-dm-{{ forloop.counter }}">
				<div class="col-md-12">
					<strong>
					{%if work.status < 6 or work.status == 7%}
					Waiting for the GMMDC decision
					{% elif work.status > 7 or work.status == 6 %}
					Accepted by the GMMDC
					{% elif work.status == 7 %}
					Rejected by the GMMDC
					{%endif%}
					</strong>
				</div>
				<div class="col-md-12">
					<strong>Comment </strong>{{ d1b.comment }}
				</div>
			</div>
			{% endif %}
			{% endfor %}<hr> {% endif %}
			{% if d2 %} 
			<div class="card-header collapsed row" data-toggle="collapse"  data-id="evalform2{{ d2.id }}"
				aria-expanded="false" href="#eval-form-2-">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-gavel"></i>&nbsp;&nbsp;&nbsp;
					{% widthratio d2.instance.score 1 6.25 %}%,&nbsp;
						<!-- 					CARD HEADING --> 
						Judge 2 ({{ d2.instance.author.last_name }}, {{ d2.instance.author.first_name }})</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row collapse card-body" id="eval-form-2-">
				<div class="col-md-12 form-section">
				<div class="row">
					{% for x, y in d2.fields.math.base_field.choices %} {% if x != '' and x in d2.instance.math %}
						<div class="form-check col-md-6">
							<input class="form-check-input disabled" type="checkbox"
								id="inlineCheckbox{{ x }}" value="{{ x }}" name="math"  checked><label
								class="form-check-label" for="inlineCheckbox{{ x }}">{{ y }}</label>
						</div>
					{% endif %} {% endfor %}
				</div>
				<hr>
					<div class="col-md-12">
						<strong>Was the mathematics correctly applied? </strong>
						<span class="qanswer">{{ d2.instance.q1 }}</span>
					</div>
					<div class="col-md-12">
						<strong>How well was the connection between mathematics and the artwork explained in the paragraph?</strong>
						<span class="qanswer">{{ d2.instance.q2 }}</span>
					</div>
					<div class="col-md-12">
						<strong>How creative/original/clever is the connection with mathematics?</strong>
						<span class="qanswer">{{ d2.instance.q3 }}</span>
					</div>
					<div class="col-md-12">
						<strong>How clear is the Mathematics visually portrayed in the artwork?</strong>
						<span class="qanswer">{{ d2.instance.q4 }}</span>
					</div>
				<hr>
					<div class="col-md-12">
						<strong>Comment</strong>
						{{ d2.instance.comment }}
					</div>
				</div>
			</div>
			 <hr>{% endif %}
			{% if d3 %} {% for evalform3 in d3 %}
			<div class="card-header collapsed row" data-toggle="collapse" data-id="evalform3{{ evalform3.id }}"
				aria-expanded="false" href="#eval-form-3-{{ forloop.counter }}">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-gavel"></i>
					&nbsp;&nbsp;&nbsp;
					{{ evalform3.score }}%,&nbsp;
						<!-- 					CARD HEADING --> 
						Judge 3 ({{ evalform3.author.last_name }}, {{ evalform3.author.first_name }})</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row collapse card-body" id="eval-form-3-{{ forloop.counter }}">
				<div class="col-md-12 form-section">
					<div class="col-md-12">
						<strong>The Explanation given of the use of Mathematics in the paragraph </strong> <span
							class="qanswer">{{ evalform3.q1 }}</span>
					</div>
					<div class="col-md-12">
						<strong>The creative connection of the artwork to Mathematics </strong> <span class="qanswer">{{ evalform3.q2 }}</span>
					</div>
					<div class="col-md-12">
						<strong>How clearly the maths is depicted in the artwork? </strong> <span class="qanswer">{{ evalform3.q3 }}</span>
					</div>
					<div class="col-md-12">
						<strong>Originality</strong> <span class="qanswer">{{ evalform3.q4 }}</span>
					</div>
					<div class="col-md-12">
						<strong>Quality of artistic composition and design </strong> <span class="qanswer">{{ evalform3.q5 }}</span>
					</div>
					<div class="col-md-12">
						<strong>Comment</strong> {{ evalform3.comment }}
					</div>
				</div>
			</div>
			{% endfor%}<hr> {%endif%}
		{%endif%}
	</div>
</div>
<div class="col-md-2"></div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$(".qanswer").each(function(){
		$(this).html(getTitle($(this).html()))
	})
})
function getTitle(intval){
	if(intval== 0)
		return "None"
	else if (intval == 1)
		return "Minimal"
	else if (intval == 2)
		return "Average"
	else if (intval == 3)
		return "Good"
	else if (intval == 4)
		return "Excellent"
}
</script>