account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views_account
from django.urls.conf import include

app_name = 'account'

urlpatterns = [
    path('login/', views_account.login_form, name='login'),
    path('forgotpsw/', views_account.forgot_psw, name='forgotpsw'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('change_password/',
          views_account.CustomPasswordChangeView.as_view(
            template_name='change_password.html', success_url="/"), name='change_password'),
    path('reset_password_confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
            template_name='reset_password_confirm.html', success_url="/?message=The%20password%20is%20successfully%20changed&T=false"), name='reset_password_confirm'),
    path('reset_password/',
          auth_views.PasswordResetView.as_view(
            template_name='reset_password.html',
            email_template_name='reset_password_email.html', success_url="/?message=A%20confirmation%20email%20is%20sent%20to%20your%20email%20address&T=false"), name='reset_password'),
    path('userlist/', views_account.projectUserList, name='userlist'),
    path('register/', views_account.registration, name='register'),
    path('register_judge/', views_account.registerJudge, name='registerJudge'),
]

artwork/urls.py
from django.urls import path
from . import rest_views
from artwork import artwork_view

app_name = 'artwork'

urlpatterns = [
    # re_path(r'^index/$', views.index, name='index'),
    path('rest_work_list', rest_views.worklists),
    path('rest_work_list_judge', rest_views.rest_work_list_judge),
    path('get_school', rest_views.get_school),
    path('flag_work', rest_views.flag_work),
    path('allocate_form', rest_views.allocate_form),
    path('', artwork_view.index, name='index'),
    path('entry_form/', artwork_view.entry_form, name='entry_form'),
    path('entry_form_view/', artwork_view.entry_form_view, name='entry_form_view'),
    path('aboutus/', artwork_view.aboutus, name='aboutus'),
    path('contactus/', artwork_view.contactus, name='contactus'),
    path('faq/', artwork_view.faq, name='faq'),
    path('history/', artwork_view.history, name='history'),
    path('manager_console/', artwork_view.managerConsole, name='manager_console'),
    path('howtoenter/', artwork_view.howtoenter, name='howtoenter'),
    path('rules/', artwork_view.rules, name='rules'),
    path('signup_page/', artwork_view.signup_page, name='signup_page'),
    path('home/', artwork_view.home, name='home'),
    path('gallery/', artwork_view.gallery, name='gallery'),
    path('work_lists/', artwork_view.work_lists, name='work_lists'),
    path('work_lists_checkbox/', artwork_view.work_lists_checkbox, name='work_lists_checkbox'),
    path('getfile/', artwork_view.getfile, name='getfile'),
    path('importfile/', artwork_view.importfile, name='importfile'),
    path('work_detail_update/', artwork_view.work_detail_update, name='work_detail_update'),
    path('<int:id>/<int:view>/', artwork_view.work_details, name='work_details'),
    path('update_work_status', rest_views.update_work_status),
]

mathart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('artwork.urls', namespace='artwork')),
    path('evaluation/', include('evaluation.urls', namespace='evaluation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class ProjectUser(AbstractUser):
    USER_TYPE_CHOICES = (
      (1, 'student'),
      (2, 'teacher'),
      (3, 'judge1'),
      (4, 'judge2'),
      (5, 'judge3'),
      (6, 'admin'),
    )

    user_type = models.PositiveSmallIntegerField(null=True, choices=USER_TYPE_CHOICES, default=1)

artwork/models.py
from django.db import models
from django.template.defaultfilters import default
import os
from uuid import uuid4
from .utils import Status


class School(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    address = models.CharField(max_length=500)
    province = models.IntegerField(default=0,blank=False,null=False)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

def path_and_rename(path):
    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(path, filename)
    return wrapper

class Artwork(models.Model):
    firstname = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.CharField(blank=True, null=True, max_length=100)
    dob = models.DateField(blank=True, null=True)
    cellphone = models.CharField(blank=True, null=True, max_length=100)
    learnergrade = models.CharField(blank=True, null=True, max_length=100)
    parentname = models.CharField(blank=True, max_length=200)
    parentphone = models.CharField(blank=True, null=True, max_length=100)
    parentemail = models.CharField(blank=False, null=False, max_length=100)
    school = models.CharField(blank=False, null=False, max_length=100)
    teachername = models.CharField(blank=True, max_length=300)
    teacherphone = models.CharField(blank=False, null=True, max_length=100)
    teacheremail = models.CharField(blank=False, null=True, max_length=100)
    worktitle = models.CharField(blank=False, null=True, max_length=300)
    workfile = models.FileField(upload_to='works')
    workfileCropped = models.TextField(blank=False, default="", null=False)
    workformulafile = models.FileField(null=True, blank='True',upload_to='formulas')
    workapproved = models.BooleanField(default=False)
    bioapproved = models.BooleanField(default=False)
    qapproved = models.BooleanField(default=False)
    question1 = models.TextField(blank=False)
    question2 = models.TextField(blank=False)
    question3 = models.TextField(blank=False)
    submitted = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=Status.statuslist(), default=-1)
    
    class Meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        print("save initiation >>> ", self)
#         if(self.id == 0):
#             handleFile()
        super(Artwork, self).save(*args, **kwargs)

    # define the returened url when the submit button hit
    def get_absolute_url(self):
        return "work_details/{self.id}"

    def __str__(self):
        return '%s %s' % (self.surname, self.firstname)

    def get_artwork_status(self):
        return Status(self.status).name

'''
#Custom Object Manager
class CustomManager(models.Model):
    def get_queryset(self):
        return super(CustomManager,
                     self).get_queryset()
                          .filter(status='approved')
'''

templates/adminPages/user_list.html
<div class="row">
	<div class="col-md-10 page-title">
		<h2>User List</h2>
	</div>
	<div class="col-md-2">
		<button class="btn btn-sm btn-success btn-block"
			onclick="showDialogPage(this, '{% url 'account:registerJudge' %}')">
			<i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;New User
		</button>
	</div>
</div>
<div class="col-md-12" id="judge-list">
	<table class="table table-general-style">
		<thead>
			<tr>
				<th scope="col">Email</th>
				<th scope="col">Full Name</th>
				<th scope="col">User Type</th>
				<th scope="col">Organisation</th>
				<th scope="col">Cellphone</th>
				<th scope="col">Edit</th>
				<th scope="col">Remove</th>
			</tr>
		</thead>
		<tbody>
			{% for user in userlist %}
			<tr>
				<td>{{ user.username }}</td>
				<th scope="row">{{ user.last_name }}, {{ user.first_name }}</th>
				<td>{{ user.get_user_type_display }}</td>
				<td>{{ user.organisation }}</td>
				<td>{{ user.cellphone }}</td>
				<td><button class="btn btn-outline-success" type="button"
						onclick="showDialogPage(this, '/account/register_judge?username={{ user.username }}')">
						<i class="fa fa-edit"></i>
					</button></td>
				<td><button class="btn btn-outline-danger disabled" type="button"
						onclick="toggleMessageBox('Not a valid action',true)">
						<i class="fa fa-trash-alt"></i>
					</button></td> {% endfor %}
			</tr>
		</tbody>
	</table>
</div>

templates/adminPages/work_details.html
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<h4>
			<strong>Status&nbsp;</strong>{{ work.get_status_display }}
		</h4>
	</div>
	<div class="col-md-2"></div>
</div>
<hr>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
			<div class="card-header collapsed row" data-toggle="collapse"
				aria-expanded="false" href="#artwork-section">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-palette"></i>&nbsp;&nbsp;&nbsp;Artwork</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="collapse card-body" id="artwork-section">
				<div class="row report-section">
					{% if work.workfile %}
					<div class="col-md-12">
						<img type="file" id="workfileCropped"
							src="{{ work.workfile.url }}">
					</div>
					{% endif %}
					<div class="col-md-12">
						<h3>
							<strong>Artwork </strong>"{{ work.worktitle | default_if_none:'Not Available'}}"
						</h3>
					</div>
					<div class="col-md-12 ">
						<h5>
							<strong>Serial</strong>
							<!-- 							SERIAL NUMBER -->
							{{ sno }}
						</h5>
					</div>
				</div>
			</div>
			{% if user.user_type != 4 and user.user_type != 5 %}
			<div class="card-header collapsed row" data-toggle="collapse"
				aria-expanded="false" href="#artist-section">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-user"></i>&nbsp;&nbsp;&nbsp;MathArtist</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="collapse card-body" id="artist-section"
				data-title="Upload my artwork">
				<div class="row report-section ">
					<div class="col-md-6">
						<h6>
							<strong> {{ fname_lname }}</strong><br> <br> <strong>Born
								in </strong>{{ work.owner.dob }} <br>
							<!-- 								USER EMAIL -->
							<strong>Email </strong>{{ work.owner.email }} <br> <strong>Cell
								phone </strong>{{ work.owner.cellphone }}
						</h6>
					</div>
					<div class="col-md-6">
						<h6>
							<strong>Grade </strong>{{ work.learnergrade | default_if_none:'Not Available'}}<br>
							<!-- PROVINCE -->
							{% if work.school %}
							{{ work.school.get_province_display }}<br>{% endif %} <strong>School</strong>
							<!-- SCHOOL INFO -->
							{% if work.school %}
							{{work.school.name }}
							{% else %}
							Not Available
							{% endif %}
						</h6>
						<h6>
							<strong>Teacher</strong> {{ work.teachername | default_if_none:'Not Available'}}<br> <strong>Email</strong>
							{{ work.teacheremail | default_if_none:'Not Available'}}
						</h6>
					</div>
					<div class="col-md-12">
						<h6>
							<strong>Parent Name</strong> {{ work.owner.parentname }}<br>
							<strong>Cell</strong> {{ work.owner.parentphone }}<br> <strong>Email</strong>
							{{ work.owner.parentemail | default_if_none:'Not Available'}}
						</h6>
					</div>
				</div>
			</div>
			{%endif%}
			<div class="card-header collapsed row" data-toggle="collapse"
				aria-expanded="false" href="#questions-section">
				<div class="col-md-11">
					<a class="card-title"><i class="fa fa-square-root-alt"></i>&nbsp;&nbsp;&nbsp;Questions</a>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="collapse card-body" id="questions-section">
				<div class="row report-section">
				<div class="col-md-6">
					<h6>
						<strong>Question 1: What Mathematics did you use in your
							artwork?</strong>
						<h6>
				</div>
				<div class="col-md-6">
					<h6>{{ work.question1 | default:'Not Available'}}</h6>
				</div>
				{% if work.workformulafile %}
				<div class="col-md-6">
					<label for="formulaImg"><h6>
							<strong>Formula Image</strong>
						</h6></label>
				</div>
				<div class="col-md-6">
					<img id="formulaImg" src="{{ work.workformulafile.url }}"
						width="100%" height="auto">
				</div>
				{% endif %} 
				<div class="col-md-6">
					<h6>
						<strong>Question 2: How did you use creativity to connect
							Mathematics with "My Universe" to make your artwork?</strong>
						<h6>
				</div>
				<div class="col-md-6">
					<h6>{{ work.question2 | default:'Not Available'}}</h6>
				</div>
				<div class="col-md-6">
					<h6>
						<strong>Question 3: Do you think creativity could be used
							to teach Mathematics?</strong>
						<h6>
				</div>
				<div class="col-md-6">
					<h6>{{ work.question3 | default:'Not Available'}}</h6>
				</div>
				<input type="hidden" name="id" id="work_id" value="{{ work.id }}"
					class="form-control form-input"> <input type="hidden"
					name="status" value="{{ work.status }}"
					class="form-control form-input status-values">
			</div>
			</div>
		<div class="col-md-2"></div>
	</div>
</div>
<hr>
<div class="evaluation-forms-div">
</div>
<hr>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		{%if work.status == 0 or work.status == 2 %}
		<!-- 		IF ITS ADMIN -->
		{%if user.user_type == 6 and view == 0 %}
		<hr>
		<div class="row" data-title="Eligible/Revision/Reject">
			<div class="col-md-12" id="">
				<form method="post" id="entry-approval-form"
					action="{% url 'artwork:work_detail_update' %}"
					class="needs-validation form-general-style"
					enctype="multipart/form-data" novalidate>
					{% csrf_token %}
					<div class="row form-section"
						data-title="Validate the entry format">
						<div class="col-md-3 form-group">
							<label for="bioapproved">Bio is acceptable</strong> <input
								type="checkbox" name="bioapproved" id="bioapproved"
								value="{{ work.bioapproved }}" class="form-control form-input">
						</div>
						<div class="col-md-3 form-group">
							<label for="workapproved">Artwork is uploaded properly</strong> <input
								type="checkbox" name="workapproved" id="workapproved"
								class="form-control form-input"
								value="{{ work.workapproved|default_if_none:'on'}}">
						</div>
						<div class="col-md-3 form-group">
							<label for="qapproved">All 3 questions are answered</strong> <input
								type="checkbox" name="qapproved" id="qapproved"
								value="{{ work.qapproved }}" class="form-control form-input">
						</div>
						<div class="col-md-3 form-group">
							<label for="comment1">Comment</strong> <textarea type="checkbox"
									name="comment" id="comment" class="form-control form-input"
									rows="5" cols="100" placeholder="Any comments">{{ work.comment }}</textarea>
						</div>
					</div>
					<input type="hidden" name="id" value="{{ work.id }}"
						class="form-control form-input"> <input type="hidden"
						name="status" value="{{ work.status }}"
						class="form-control form-input status-values">
					<div class="row form-section" data-title="Decision">
						<div class="col-md-4">
							<button class="btn btn-success btn-block" type="button"
								id="approveBTN0"><i class="fa fa-check-circle">&nbsp;&nbsp;&nbsp;</i>Approve</button>
						</div>
						<div class="col-md-4">
							<button class="btn btn-outline-warning btn-block" type="button"
								id="reviseBTN0"><i class="fa fa-edit">&nbsp;&nbsp;&nbsp;</i>Requires Revision</button>
						</div>
						<div class="col-md-4">
							<button class="btn btn-outline-danger btn-block" type="button"
								id="rejectBTN0">
								<i class="fa fa-times-circle">&nbsp;&nbsp;&nbsp;</i>Reject
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- 	FORM D1-a - JUDGE 1 -->
		{% endif %} {% elif work.status == 4 or work.status == 5 %}
		<!-- 		IF ADMIN OR JUDGE 1 -->
		{%if user.user_type == 2 or user.user_type == 6 %}
		<div class="row">
			<div class="col-md-12" id="form-d1a"></div>
		</div>

		<!-- 	FORM D1-b - DECISION MAKER -->

		{% endif %} 
		<!-- 		IF ADMIN OR Decision Maker -->
		{%if user.user_type == 3 or user.user_type == 6 %}
		<div class="row">
			<div class="col-md-12" id="form-d1b"></div>
		</div>

		<!-- 	FORM D2  -->

		{% endif %} {% elif work.status == 6 %}
		<!-- 		IF ADMIN OR JUDGE 2 -->
		{%if user.user_type == 4 or user.user_type == 6%}
		<div class="row">
			<div class="col-md-12" id="form-d2"></div>
		</div>

		<!-- 	FORM D3 - JUDGE 3 -->

		{% endif %} {%elif work.status == 10 %}
		<!-- 		IF ADMIN OR JUDGE 3 -->
		{%if user.user_type == 5 or user.user_type == 6 %}
		<div class="row">
			<div class="col-md-12" id="form-d3"></div>
		</div>
		{% endif %} {%endif%}
	</div>
	<div class="col-md-2"></div>
</div>
<script type="text/javascript">
	$(document).ready(
			function() {
				{% if view == 0 %}
				{% if work.status == 4 or work.status == 5 %}
				$("#form-d1a").load(
						'/evaluation/formd1a?work_id=' + $("#work_id").val(),
						function() {
							$("#buttonSubmitD1AForm").click(function(ev) {
								ev.preventDefault()
							})
						})
					{%if user.user_type == 3 or user.user_type == 6 %}	
				$("#form-d1b").load(
						'/evaluation/formd1b?work_id=' + $("#work_id").val(),
						function() {
							$("#buttonSubmitD2Form").click(function(ev) {
								ev.preventDefault()
							})
							$(".evaluation-forms-div").load("/evaluation/eval_forms_artwork?work_id=" + $("#work_id").val())
						})
						{% endif %}
					{% elif work.status == 6 %}
				$("#form-d2").load(
						'/evaluation/formd2?work_id=' + $("#work_id").val())
					{% elif work.status == 10 %}
				$("#form-d3").load(
						'/evaluation/formd3?work_id=' + $("#work_id").val(),
						function() {
							$("#buttonSubmitD2Form").click(function(ev) {
								ev.preventDefault()
							})
						})
				{% endif %}
				{% endif %}
				$("#approveBTN0").click(function(ev) {
					ev.preventDefault()
					validateSubmission(0)
				})
				$("#reviseBTN0").click(function(ev) {
					ev.preventDefault()
					validateSubmission(1)
				})
				$("#rejectBTN0").click(function(ev) {
					ev.preventDefault()
					validateSubmission(2)
				})
				{%if view == 1 %}
					{%if user.user_type == 3 or user.user_type == 6 or user.user_type == 7 %}	
					$(".evaluation-forms-div").load("/evaluation/eval_forms_artwork?work_id=" + $("#work_id").val())
					{% endif %}
				{% endif %}
			})
</script>

templates/adminPages/work_lists.html
<style>
.centered {
	text-align: center;
}
</style>
<div class="row">
	<div class="col-md-10 page-title">
		<h2>Artwork List</h2>
	</div>
	<div class="col-md-2"></div>
</div>
<div class="photo-viewer"></div>
{% if user.user_type == 6 or user.user_type == 7 %}
<div class="row">
	<div class="col-md-3">
		<label for="status">Filter Status</label> <select
			onchange="changeView(this)" class="form-control form-input"
			id="statuses"><option value="-2">All</option>
			<option value="-1">Pending</option>
			<option value="0">Submitted</option>
			<option value="1">Required Revision</option>
			<option value="2">Revised Work</option>
			<option value="3">Rejected Entry</option>
			<option value="4">Accepted Entry</option>
			<option value="5">Waiting for GMMDC Decision</option>
			<option value="6">Accepted by GMMDC</option>
			<option value="7">Rejected by GMMDC</option>
			<option value="8">Waiting for Posting Artwork</option>
			<option value="9">Rejected by Judge2</option>
			<option value="10">Artwork Received</option>
			<option value="11">Rejected at the Final Stage</option>
			<option value="12">Winner</option>
		</select>
	</div>
	<div class="col-md-3">Number of learners: {{numberoflearners}}</div>
	<div class="col-md-3">Submitted works: {{numberofartworks}}</div>
</div>
{%endif%}
<script type="text/javascript">
$("#statuses").val({{request.GET.status}})
function changeView(select) {
	$(".frameLoding").fadeIn()
	$('#admin-console-content').load("/work_lists?status="+$("#statuses").val(),function() {
		$(".frameLoding").fadeOut()
	})
}
</script>
<table class="table table-general-style">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Work Title</th>{% if user.user_type == 6 or user.user_type == 7 %}
			<th scope="col">Full Name</th>
			<th scope="col">Status</th>
			<th scope="col">School</th>
			<th scope="col">Grade</th> 
			<th scope="col" class="centered">Flag</th> 
			<th scope="col" class="centered">View</th> {% endif %}
			<th scope="col" class="centered">Evaluate</th> 
			{% if user.user_type == 6 %}
			<th scope="col" class="centered">Edit</th>
			<th scope="col" class="centered">Learner</th>
<!-- 			<th scope="col" class="centered">Remove</th> -->
			 {% endif %}
		</tr>
	</thead>
	<tbody>
		{% for work in works %}
		<tr class="row-hover">
			<td>{{ forloop.counter }}</td>
			<td>{{ work.worktitle }} {%if work.thumbnail.url != None %}
				<div class="artwork-thumbnail">
					<img class="img-thumbnail" src='{{ work.thumbnail.url }}'>
				</div> {%endif%}
			</td>
			{% if user.user_type == 6 or user.user_type == 7 %}
			<td>{{ work.owner.last_name }}, {{ work.owner.first_name }}</td>
			<td>{{ work.get_status_display }}</td>
			<td>{{ work.school.name }}</td>
			<td>{{ work.learnergrade }}</td> 
			<td><button
					class="btn flag-icon {% if work.flagged %} btn-warning {% else %} btn-outline-warning {% endif %}"
					type="button" {% if user.user_type == 6 %}
					onclick="flagit(this, {{ work.id }})"
					{% endif %}
					id="flag-btn-{{ work.id }}">
					<i class="fa fa-font-awesome-flag"></i>
				</button></td> 
			<td class="centered"><button class="btn btn-outline-info"
					type="button"
					onclick="showDialogPage(this, '{% url 'artwork:work_details' work.id 1 %}')">
					<i class="fa fa-eye"></i>
				</button></td> {% endif %}
			<td class="centered"><button class="btn btn-outline-info"
					type="button"
					onclick="showDialogPage(this, '{% url 'artwork:work_details' work.id 0 %}')">
					<i class="fa fa-gavel"></i>
				</button></td> {% if user.user_type == 6 %}
			<td class="centered"><button
					class="btn btn-outline-info" type="button"
					onclick="window.open('/admin/artwork/artwork/{{work.id}}/change/')">
					<i class="fa fa-edit"></i>
				</button></td>
			<td class="centered"><button
					class="btn btn-outline-info" type="button"
					onclick="window.open('/admin/account/projectuser/{{work.owner.id}}/change/')">
					<i class="fa fa-user"></i>
				</button></td>
<!-- 			<td class="centered"><button -->
<!-- 					class="btn btn-outline-danger disabled" type="button" -->
<!-- 					onclick="toggleMessageBox('Not a valid action',true)"> -->
<!-- 					<i class="fa fa-trash-alt"></i> -->
<!-- 				</button></td> -->
				{% endif %}
		</tr>
		{% endfor %}
	</tbody>
</table>
<script>
setTimeout(function(){
	$("tr.row-hover").each(function() {
		$(this).mouseenter(function() {
			$(".photo-viewer").html($(this).find(".artwork-thumbnail").html())
			TweenLite.to(".photo-viewer", .2, {
				scale: 1,
				"z-index": 11,
				opacity: 1,
				transformOrigin: "center"
			})
			TweenLite.to($(this), .2, {
				"z-index": 10,
				transformOrigin: "center",
				"box-shadow": "black 0px 0px 11px"
			})
		})
		$(this).mouseleave(function(){
			$(".photo-viewer").html("")
			TweenLite.to(".photo-viewer", .2 , {
				scale: 0,
				opacity: 0,
				"z-index": 1,
				transformOrigin: "center"
			})
			TweenLite.to($(this), .2, {
				"z-index": 1,
				transformOrigin: "center",
				"box-shadow": "none"
			})
		})
	})
}, 200)
</script>

templates/adminPages/work_lists_checkbox.html
<style>
.centered {
	text-align: center;
}
.row-hover{
	cursor: pointer;
}
</style>
<div class="row">
	<div class="col-md-10 page-title">
		<h2>Allocate Artwork to {{ request.GET.judge }} ({{request.GET.grade}}) 
		<input type="hidden" id="gradeValue" value="{{request.GET.grade}}">
		<input type="hidden" id="username" value="{{ request.GET.judge }}">
		</h2>
	</div>
	<div class="col-md-2"></div>
</div>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<button class="btn btn-info btn-sm"
			onclick="showDialogPage(this, '/account/register_judge?username={{request.GET.judge}}')">
			<i class="fa fa-reply">&nbsp;</i>Back
		</button>
	</div>
<div class="photo-viewer"></div>
<table class="table table-general-style">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Full Name</th>
			<th scope="col">Status</th>
			<th scope="col">Work Title</th>
			<th scope="col">School</th>
			<th scope="col">Grade</th> 
		</tr>
	</thead>
	<tbody>
		{% for work in works %}
		<tr class="row-hover" onclick="allocateArtworkToJudge('{{ request.GET.judge }}','{{ work.id }}',true)">
			<td>{{ forloop.counter }}</td>
			<td>{{ work.owner.last_name }}, {{ work.owner.first_name }}</td>
			<td>{{ work.get_status_display }}</td>
			<td>{{ work.worktitle }} {%if work.thumbnail.url != None %}
				<div class="artwork-thumbnail">
					<img class="img-thumbnail" src='{{ work.thumbnail.url }}'>
				</div> {%endif%}
			</td>
			<td>{{ work.school.name }}</td>
			<td>{{ work.learnergrade }}</td> 
		</tr>
		{% endfor %}
	</tbody>
</table>
<script>
setTimeout(function(){
	$("tr.row-hover").each(function() {
		$(this).mouseenter(function() {
			$(".photo-viewer").html($(this).find(".artwork-thumbnail").html())
			TweenLite.to(".photo-viewer", .2, {
				scale: 1,
				"z-index": 11,
				opacity: 1,
				transformOrigin: "center"
			})
			TweenLite.to($(this), .2, {
				"z-index": 10,
				transformOrigin: "center",
				"box-shadow": "black 0px 0px 11px"
			})
		})
		$(this).mouseleave(function(){
			$(".photo-viewer").html("")
			TweenLite.to(".photo-viewer", .2 , {
				scale: 0,
				opacity: 0,
				"z-index": 1,
				transformOrigin: "center"
			})
			TweenLite.to($(this), .2, {
				"z-index": 1,
				transformOrigin: "center",
				"box-shadow": "none"
			})
		})
	})
}, 200)

</script>