account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views_account
from django.urls.conf import include

app_name = 'account'

urlpatterns = [
    path('login/', views_account.login_form, name='login'),
    path('forgotpsw/', views_account.forgot_psw, name='forgotpsw'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('change_password/',
          views_account.CustomPasswordChangeView.as_view(
            template_name='change_password.html', success_url="/"), name='change_password'),
    path('reset_password_confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
            template_name='reset_password_confirm.html', success_url="/?message=The%20password%20is%20successfully%20changed&T=false"), name='reset_password_confirm'),
    path('reset_password/',
          auth_views.PasswordResetView.as_view(
            template_name='reset_password.html',
            email_template_name='reset_password_email.html', success_url="/?message=A%20confirmation%20email%20is%20sent%20to%20your%20email%20address&T=false"), name='reset_password'),
    path('userlist/', views_account.projectUserList, name='userlist'),
    path('register/', views_account.registration, name='register'),
    path('register_judge/', views_account.registerJudge, name='registerJudge'),
]

artwork/urls.py
from django.urls import path
from . import rest_views
from artwork import artwork_view

app_name = 'artwork'

urlpatterns = [
    # re_path(r'^index/$', views.index, name='index'),
    path('rest_work_list', rest_views.worklists),
    path('rest_work_list_judge', rest_views.rest_work_list_judge),
    path('get_school', rest_views.get_school),
    path('flag_work', rest_views.flag_work),
    path('allocate_form', rest_views.allocate_form),
    path('', artwork_view.index, name='index'),
    path('entry_form/', artwork_view.entry_form, name='entry_form'),
    path('entry_form_view/', artwork_view.entry_form_view, name='entry_form_view'),
    path('aboutus/', artwork_view.aboutus, name='aboutus'),
    path('contactus/', artwork_view.contactus, name='contactus'),
    path('faq/', artwork_view.faq, name='faq'),
    path('history/', artwork_view.history, name='history'),
    path('manager_console/', artwork_view.managerConsole, name='manager_console'),
    path('howtoenter/', artwork_view.howtoenter, name='howtoenter'),
    path('rules/', artwork_view.rules, name='rules'),
    path('signup_page/', artwork_view.signup_page, name='signup_page'),
    path('home/', artwork_view.home, name='home'),
    path('gallery/', artwork_view.gallery, name='gallery'),
    path('work_lists/', artwork_view.work_lists, name='work_lists'),
    path('work_lists_checkbox/', artwork_view.work_lists_checkbox, name='work_lists_checkbox'),
    path('getfile/', artwork_view.getfile, name='getfile'),
    path('importfile/', artwork_view.importfile, name='importfile'),
    path('work_detail_update/', artwork_view.work_detail_update, name='work_detail_update'),
    path('<int:id>/<int:view>/', artwork_view.work_details, name='work_details'),
    path('update_work_status', rest_views.update_work_status),
]

mathart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('artwork.urls', namespace='artwork')),
    path('evaluation/', include('evaluation.urls', namespace='evaluation')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/baseBU.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>{% block title %} {% endblock title %}</title>
<link href="{% static 'css/bootstrap/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/styles.css' %}" rel="stylesheet">
<link href="{% static 'css/nice-select.min.css' %}" rel="stylesheet">
<link href="{% static 'css/buttons.style.css' %}" rel="stylesheet">
<link href="{% static 'css/form.style.css' %}" rel="stylesheet">
<link href="{% static 'css/table.style.css' %}" rel="stylesheet">
<link href="{% static 'css/menu.style.css' %}" rel="stylesheet">
<link href="{% static 'css/content.style.css' %}" rel="stylesheet">

<script src="{% static 'js/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/GSAP/TweenMax.min.js' %}"></script>
<script src="{% static 'js/jquery/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/jquery/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/math.js' %}"></script>

</head>

<body>
	<div class="container" id="main-body">
		<div class="full-screen-div"></div>
		<div class="message-box-container">
			<div class="message-box error-message-box"></div>
			<div class="message-box success-message-box"></div>
			<div class="return-button" onclick="toggleMessageBox(null, null)">
			</div>
		</div>
		<div class="menu-items-holder menu-items-holder-top">
			<ul class="menu-items menu-top">
				<!-- 					<li class="menu-item" id="about-us" -->
				<!-- 						data-href="{% url 'artwork:aboutus' %}"><img -->
				<!-- 						src="static/img/icons/about.svg"><span>About Us</span></li> -->
				<!-- 					<li class="menu-item" id="gallery" -->
				<!-- 						data-href="{% url 'artwork:gallery' %}"><img -->
				<!-- 						src="static/img/icons/art-gallery.svg"><span>Gallery</span></li> -->
				<li class="menu-item" id="contact-us"
					data-href="{% url 'artwork:contactus' %}"><img
					src="static/img/icons/contact.svg"><span>Contact Us</span></li>
			</ul>
		</div>

		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">Navbar</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse"
				data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active"><a class="nav-link" href="#">Home
							<span class="sr-only">(current)</span>
					</a></li>
					<li class="nav-item"><a class="nav-link" href="#">Link</a></li>
					<li class="nav-item dropdown"><a
						class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
						role="button" data-toggle="dropdown" aria-haspopup="true"
						aria-expanded="false"> Dropdown </a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a> <a
								class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div></li>
					<li class="menu-item" id="contact-us"
						data-href="{% url 'artwork:contactus' %}"><img
						src="static/img/icons/contact.svg"><span>Contact Us</span></li>
					<li class="nav-item"><a class="nav-link disabled" href="#">Disabled</a>
					</li>
				</ul>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search"
						placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</nav>



		<!-- 			<div class="menu-items-holder menu-items-holder-left"> -->
		<ul class="menu-items menu-top">
			{% if user.is_authenticated and user.user_type == 6%}
			<li class="menu-item" id="about-us"
				data-href="{% url 'artwork:work_lists' %}"><img
				src="static/img/icons/document.svg"><span>Artwork List</span></li>
			{% endif %}
			<!-- 					<li class="menu-item" id="about-us" -->
			<!-- 						data-href="{% url 'artwork:history' %}"><img -->
			<!-- 						src="static/img/icons/history.svg"><span>History</span></li> -->
			<!-- 					<li class="menu-item" id="sign-up" -->
			<!-- 						data-href="{% url 'artwork:howtoenter' %}"><img -->
			<!-- 						src="static/img/icons/entrance.svg"><span>How to -->
			<!-- 							Enter</span></li> -->
			<!-- 					<li class="menu-item" id="sign-up" -->
			<!-- 						data-href="{% url 'artwork:rules' %}"><img -->
			<!-- 						src="static/img/icons/document.svg"><span>Rules</span></li> -->
			{% if user.is_authenticated and user.user_type == 1%}
			<li class="menu-item" id="sign-up"
				data-href="{% url 'artwork:signup_page' %}"><img
				src="static/img/icons/trophy.svg"><span>Submit Artwork
			</span></li> {% endif %}

			<!-- 					<li class="menu-item" id="contact-us" -->
			<!-- 						data-href="{% url 'artwork:faq' %}"><img -->
			<!-- 						src="static/img/icons/information.svg"><span>FAQ</span></li> -->
		</ul>

		<!-- 			</div> -->
		<div class="page-content">{% block content %}</div>
		<!-- 		</div> -->

		{% if user.is_authenticated %}
		<div class="form-section">
			<img class="user-icon" src="static/img/icons/user.svg">
			<p style="display: inline-block;">
			<h4 style="display: inline-block; padding-left: 22px;">{{
				user.get_username }}</h4>
			</p>
			<div class="row">
				<div class="col-md-9">
					<a href="#">Change Password</a>
				</div>
				<div class="col-md-3">
					<a href="{% url 'account:logout' %}">Logout</a>
				</div>
			</div>
		</div>
		{% else %}
		<div id="login-div"></div>
		{% endif %}
		<footer class="my-5 pt-5 text-muted text-center text-small">
			<p class="mb-1">&copy; 2019 Company Name</p>
			<ul class="list-inline">
				<li class="list-inline-item"><a href="#">Privacy</a></li>
				<li class="list-inline-item"><a href="#">Terms</a></li>
				<li class="list-inline-item"><a href="#">Support</a></li>
			</ul>
		</footer>
	</div>
	{% endblock %}
</body>

</html>

templates/change_password.html
	<form action="{% url 'account:change_password' %}" method="post"
		class="form-group login-form">
		{% csrf_token %} {{ form.as_p }}
		<button type="submit" class="input-group btn btn-primary btn-sm mb-3">
			<i class="fa fa-lock-open"></i>&nbsp;Change Password
		</button>
	</form>

templates/dashindex.html
{% extends "basedash.html" %}
{% block title %}Mathart Project{% endblock %}
{% block nav-dashindex %}
  <a class="nav-link active" href="{% url 'artwork:dashindex' %}">
    <span data-feather="home"></span>
    Worklists <span class="sr-only">(current)</span>
  </a>{% endblock %}

  {% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Worklists</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>
      <div class="row">
        <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">School</th>
          <th scope="col">Surname</th>
          <th scope="col">Name</th>
          <th scope="col">Work Title</th>
          <th scope="col">Email</th>
          <th scope="col">Age</th>
          <th scope="col">Grade</th>
          <th scope="col">WorkFile</th>
          <th scope="col"><th>
        </tr>
      </thead>
      <tbody>
      {% for work in works %}
       <tr>
         <th scope="row">{{ work.id }}</th>
         <td>{{ work.school }}</td>
         <td>{{ work.surname }}</td>
         <td>{{ work.firstname }}</td>
         <td>{{ work.worktitle }}</td>
         <td>{{ work.email }}</td>
         <td>{{ work.age }}</td>
         <td>{{ work.learnergrade }}</td>
         <td>
           <img class="img-thumbnail" height="100" width="100" src='{{ work.workfile.url }}'>
         </td>
         <td><a href="{% url 'artwork:work_details' work.id %}">Details</td>
       </tr>
       {% endfor %}
     </tbody>
    </table><a href="{{ work.get_absolute_url }}"><a href="{{ work.get_absolute_url }}"><a href="{{ work.get_absolute_url }}">
    </main>

    {% endblock %}

templates/history.html
<style>
.replaced-svg.svgNonMenu {
	width: 222px;
}
</style>
<div class="row" id="banner-top">
	<div class="col-md-12 banners-text-content">
		<img alt="" src="static/img/graphics/Inspiringbar5.png">
	</div>
</div>
<div class="row page-content-holder">
	<div class="col-md-2 splatter-7"></div>
	<div class="col-md-8">
		<div class="col-md-12 page-title">
			<h2>Competition History</h2>
		</div>
		<div class="col-md-12" style="text-align: center; font-size: 33px;">
			<a href="static/files/mathart-competition-rules.pdf"
				class="btn btn-link" download><img
				alt="" src="static/img/graphics/Big Buttons/Printbutton.svg"
				class="svgNonMenu"> </a>
		</div>
		<br>
		<div class="row">
			<div class="col-md-12">
				<p>The Math-Art competition is an innovative, practical project
					that resulted from the need to promote creativity in problem
					solving by encouraging learners to explore the real-life links
					between mathematics and the arts (which is one of the main aims of
					the STEAM concept in education). The Govan Mbeki Mathematics
					Development Centre (GMMDC) based at the Nelson Mandela University
					adopted the STEAM concept in 2017 as one of the important
					educational drivers of the future.</p>
			</div>
			<div class="col-md-12">
				<p>The GMMDC launched the MathArt competition project in high
					schools of the Eastern Cape Province in March 2018. The MathArt
					competition was piloted with the support of the Nelson Mandela
					University's School of Music, Art and Design (SoMAD) and the
					Department of Basic Education in the Eastern Cape Province.
					Entrants were required to come up with their own concept of
					MathArt, within a suggested project theme. Each entry had to
					include a 300-word description of how their artwork linked
					mathematics and art. There were two age categories in 2018: Grades
					8 & 9 and Grades 10 to 12. Judging was mostly based on the
					creativity in linking mathematics and art.</p>
			</div>
			<div class="col-md-12">
				<p>The regional pilot competition in 2018 was overwhelmingly
					successful. It attracted 113 entries, mostly from learners in 36
					previously-disadvantaged schools in the Eastern Cape. Most of the
					entries were exhibited at the Nelson Mandela Metropolitan Art
					Museum in Port Elizabeth in May that year.</p>
			</div>
			<div class="col-md-12">
				<p>The pilot South African MathArt project has attracted the
					attention of the international math-art community. The Experience
					Workshop Global STEAM Network (www.experienceworkshop.org), which
					have been organizing International Children and Youth Math-Art
					Exhibits since 2012, have initiated the international collaboration
					and supported the competition from the beginning. Since 2018, the
					artworks of the South African children were exhibited at the "John
					Hiigli Children and Youth Math-Art" exhibits, organized by the
					Experience Workshop at the Bridges conferences, the world's largest
					math-art community's annual meetings at various locations around
					the globe. Thirty selected MathArt entries from South Africa were
					part of this exhibit at the annual International Bridges
					Conference, which took place at the National Museum of Science and
					Technology in Stockholm, Sweden, in July 2018.</p>
			</div>
			<div class="col-md-12">
				<p>The MathArt project was expanded, with the support of Umalusi
					and the Department of Basic Education, to a national school
					competition in 2019. A total of 593 competition entries were
					received from 75 schools in the 8 provinces in South Africa in this
					year. All the entries were again exhibited at the Nelson Mandela
					Metropolitan Art Museum in Port Elizabeth in June 2019. Once again,
					a selection of the best South African entries were invited by
					Experience Workshop organizers to be exhibited at the 2019
					International Bridges Conference in July, this time in Linz,
					Austria.</p>
			</div>
			<div class="col-md-12">
				<p>Subsequently, more provincial and national education
					stakeholders in South Africa have expressed a keen interest to join
					this national project as it seeks to promote STEAM education with
					the emphasis on integrating innovation and creativity as vital
					skills to meet the challenges of the 4IR.</p>
			</div>
			<div class="col-md-12">
				<p>The collaboration between the GMMDC and the Experience
					Workshop Global STEAM Network have been fruitful and will continue
					to grow as the national MathArt school competition programme
					expands every year.</p>
			</div>
			<div class="col-md-12" style="text-align: center;">
			<img alt="#" src="static/img/graphics/Graphic elements/ExperienceWorkshopORGeng.png">
			</div>
		</div>
	</div>
	<div class="col-md-2 splatter-8"></div>
</div>

templates/index.html
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Cache-Control"
	content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
</head>
{% extends "base.html" %}
{% block content %}
{% endblock %}
</html>

templates/login.html
 {% if user.is_authenticated %}
 <script type="text/javascript">
	{% if user.user_type == 1 %}
		$("li[data-href='/signup_page']").trigger("click")
	{% else %}
		if(!$("#admin-page-btn").length)
			window.location.replace("/")
	{% endif %}
</script>
<div class="row" style="position: absolute; top: 3px;">
	<div class="col-md-12">
		<i class="fa fa-user"></i>&nbsp;{{ user.last_name}},
		<!-- 		USERNAME & PASSWORD -->
		&nbsp;{{user.first_name }}
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<button data-toggle="dropdown" class="btn btn-link btn-sm dropdown-toggle"
			onclick="$('.change-password-div').load('/account/change_password/')"
			href="#">
			<i class="fa fa-key"></i>&nbsp;Change Password
		</button>
		<div class="dropdown-menu change-password-div"></div>
		<button type="button" class="btn btn-outline-dark btn-sm"
			onclick="window.location.replace('{% url 'account:logout' %}')">
			<i class="fa fa-sign-out"></i>&nbsp;Logout
		</button>
	</div>
</div>

<!-- WHEN THE USER IS NOT LOGGED IN -->

{% else %}
<script type="text/javascript">
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()
		})
	</script>
<div class="dropdown">
	<button data-toggle="dropdown" class="btn btn-light dropdown-toggle"
		style="color: var(--main-color-green);" aria-haspopup="true"
		aria-expanded="false" id="dropdownMenu2">
		<i class="fa fa-sign-in-alt">&nbsp;&nbsp;&nbsp;</i>Login
	</button>
	<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
		<form action="{% url 'account:login' %}" method="post"
			class="form-group login-form login-ul" id="login-form-id">
			{% csrf_token %}
			<div class="input-group mb-3">
				<span class="input-group-addon"><i class="fa fa-user"></i></span> <input
					type="text" name="username" class="form-control input-group"
					placeholder="Email" id="inputEmail" required>
			</div>
			<div class="input-group mb-3">
				<span class="input-group-addon"><i class="fa fa-key"></i></span> <input
					type="password" class="form-control" id="inputPassword"
					name="password" placeholder="Password" required>
			</div>
			<button type="button" id="login-btn-id"
				onclick="loginForm('{% url 'account:login' %}','login-form-id','login-btn-id')"
				class="input-group btn btn-primary btn-sm mb-3">
				<i class="fa fa-lock-open"></i>&nbsp;&nbsp;&nbsp;Login
			</button>
			<button class="input-group btn btn-link btn-sm mb-3"
				onclick="showForgotPsw()" type="button">
				<i class="fa fa-question-circle"></i>&nbsp;&nbsp;&nbsp;Forgot the
				password
			</button>
		</form>
		<div class="forgot-psw">
		</div>
	</div>
</div>
{% endif %}
<script type="text/javascript">
$('.dropdown-toggle').dropdown()
</script>

templates/register2.html
<form method="post" action="{% url 'account:register' %}"
	class="needs-validation form-general-style" id="registry-form"
	enctype="multipart/form-data" novalidate>
	<div class="form-section" data-title="Registration">
		<div class="form-group row">


			<!-- 					EMAIL -->


			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i class="fa fa-at"></i></span>
				</div>
				<input type="email" class="form-control" placeholder="Email"
					required autocomplete="off" id="username" name="username"
					value="{{ user.username|default:'test@test.com' }}">
			</div>

			<!-- 				CELLPHONE -->

			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i class="fa fa-mobile"></i></span>
				</div>
				<input type="text" class="form-control" placeholder="cellphone"
					required="required" id="cellphone"
					value="{{ user.cellphone|default:'0712345678' }}"
					name="Cellphone Number">
			</div>
		</div>


		<div class="row form-group">


			<!-- 					NAME -->


			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-text">First Name</span>
				</div>
				<input type="text" class="form-control" placeholder="i.e. Joe"
					required id="first_name" name="first_name"
					value="{{ user.first_name | default:'testname' }}">
			</div>
			<!-- 				SURNAME -->

			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-text">Last Name</span>
				</div>
				<input type="text" class="form-control" placeholder="i.e. Scholtz"
					required id="last_name"
					value="{{ user.last_name | default:'lastname' }}"
					name="last_name">
			</div>
		</div>



		<div class="row form-group">


			<!-- 					Date of Birth -->


			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i
						class="fa fa-birthday-cake"></i></span>
				</div>
				<input type="date" class="form-control" required id="dob" name="dob"
					value="{{ user.dob|default:'2013-01-08' }}">
			</div>
		</div>



		<div class="row form-group">


			<!-- 					PARENT NAME -->


			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-text">Parent's Full-Name</span>
				</div>
				<input type="text" class="form-control"
					placeholder="i.e. Jack Scholtz" required id="parentname"
					name="parentname"
					value="{{ user.parentname|default:'testparentname' }}">
			</div>



			<!-- 				PARENT PHONE NUMBER -->

			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-text">Parent's Cell phone Number</span>
				</div>
				<input type="phone" class="form-control" name="parentphone"
					placeholder="012 345 67 89" id="parentphone"
					value="{{ user.parentphone|default:'081234567' }}"
					required>
			</div>
		</div>


		<!-- 				PARENT EMAIL ADDRESS-->


		<div class="row form-group">

			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i class="fa fa-at"></i></span>
				</div>
				<input type="email" class="form-control" id="parentemail"
					name="parentemail" placeholder="you@example.com" value="{{ user.parentemail|default:'testparent@test.com' }}" required>
			</div>

		</div>




		<div class="row form-group">
			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i class="fa fa-key"></i></span>
				</div>
				<input type="password" class="form-control" id="password1"
					name="password1" placeholder="Password" required value="abcdefg12345">
			</div>

			<div class="input-group col-sm-6">
				<div class="input-group-prepend">
					<span class="input-group-addon"><i class="fa fa-key"></i></span>
				</div>
				<input type="password" class="form-control" id="password2"
					name="password2" placeholder="Repeat Password" value="abcdefg12345" required>
			</div>
		</div>

		{% csrf_token %}
		<div class="row form-group">
			<div class="input-group col-sm-2"></div>
			<div class="input-group col-sm-8">
				<button class="btn btn-primary btn-success col-sm-12" type="submit" id="register-btn">Register Now</button>
			</div>
		</div>
	</div>
</form>

templates/reset_password.html
<form action="{% url 'account:reset_password' %}" method="post"
	class="form-group login-form">
	{% csrf_token %} {{ form.as_p }}
	<button type="submit" class="input-group btn btn-primary btn-sm mb-3">
		<i class="fa fa-lock-open">&nbsp;&nbsp;&nbsp;</i>Send Reset Link
	</button>
	<button type="button" id="login-btn-id"
				onclick="hideForgotPsw()"
				class="input-group btn btn-link btn-sm mb-3">
				<i class="fa fa-lock-open">&nbsp;&nbsp;&nbsp;</i>Login
			</button>
</form>

templates/reset_password_confirm.html
<form method="post"
	class="form-group login-form">
	{% csrf_token %} {{ form.as_p }}
	<button type="submit" class="input-group btn btn-primary btn-sm mb-3">
		<i class="fa fa-lock-open"></i>&nbsp;Change My Password
	</button>
</form>

templates/reset_password_email.html
To initiate the password reset process for your {{ user.get_username }}
MathartCompetition Account,

Click the link below:
{{ protocol }}://{{ domain }}{% url 'account:reset_password_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead,

Sincerely,
Mathart Admin Team